basePath: /api
definitions:
  domain.Building:
    properties:
      address:
        type: string
      name:
        type: string
      name_business_entity:
        type: string
      phone:
        type: string
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  title: Товарный рынок API
  version: "1.0"
paths:
  /api/:
    post:
      consumes:
      - application/json
      description: create a new building item
      parameters:
      - description: building
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Building'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      summary: CreateBuildingItem
swagger: "2.0"
