basePath: /
definitions:
  domain.Building:
    properties:
      availability_asu:
        type: boolean
      employee_count:
        type: integer
      form_owner_id:
        type: integer
      inn:
        type: string
      kpp:
        type: string
      micro_district_name:
        type: string
      name_building:
        type: string
      name_full_building:
        type: string
      object_type:
        type: boolean
      opening_date:
        type: string
      region_id:
        type: integer
      retail_space:
        type: integer
      self_service:
        type: boolean
      street_name:
        type: string
      total_area:
        type: integer
      trading_network_id:
        type: integer
      type_object_id:
        type: integer
      work_place_count:
        type: integer
    type: object
  domain.BuildingUpdateInput:
    properties:
      availability_asu:
        type: boolean
      closing_date:
        type: string
      employee_count:
        type: integer
      form_owner_id:
        type: integer
      inn:
        type: string
      kpp:
        type: string
      micro_district_name:
        type: string
      name_building:
        type: string
      name_full_building:
        type: string
      object_type:
        type: boolean
      opening_date:
        type: integer
      region_id:
        type: integer
      retail_space:
        type: integer
      self_service:
        type: boolean
      street_name:
        type: string
      total_area:
        type: integer
      trading_network_id:
        type: integer
      type_object_id:
        type: integer
      work_place_count:
        type: integer
    type: object
  domain.Subject:
    properties:
      form_of_owner_ship_id:
        type: integer
      full_name_subject:
        type: string
      id:
        type: integer
      inn:
        type: string
      kpp:
        type: string
      subject_name:
        type: string
    required:
    - form_of_owner_ship_id
    - full_name_subject
    - inn
    - kpp
    - subject_name
    type: object
  domain.SubjectInput:
    properties:
      form_of_owner_ship_id:
        type: integer
      full_name_subject:
        type: string
      inn:
        type: string
      kpp:
        type: string
      subject_name:
        type: string
    type: object
  domain.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
  handler.dataResponse:
    properties:
      data:
        type: object
    type: object
  handler.signInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
host: localhost:5000
info:
  contact: {}
  title: Товарный рынок API
  version: "1.0"
paths:
  /api/buildings:
    get:
      consumes:
      - application/json
      description: Get all buildings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.dataResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: GetAllBuildings
      tags:
      - Объект
    post:
      consumes:
      - application/json
      description: create a new building item
      parameters:
      - description: building
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Building'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: CreateBuildingItem
      tags:
      - Объект
  /api/buildings/:id:
    delete:
      consumes:
      - application/json
      description: delete item with id
      parameters:
      - description: building id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: DeleteBuildingItem
      tags:
      - Объект
    put:
      consumes:
      - application/json
      description: update chosen item
      parameters:
      - description: update building
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.BuildingUpdateInput'
      - description: building id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: UpdateBuildingItem
      tags:
      - Объект
  /api/subject:
    get:
      consumes:
      - application/json
      description: get all subjects
      operationId: get-all-subjects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.dataResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get All Subjects
      tags:
      - Субъект
    post:
      consumes:
      - application/json
      description: create subject
      operationId: create-subject
      parameters:
      - description: subject
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Subject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Create subject
      tags:
      - Субъект
  /api/subject/:id:
    delete:
      consumes:
      - application/json
      description: delete item with id
      parameters:
      - description: subject id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete Subject
      tags:
      - Субъект
    put:
      consumes:
      - application/json
      description: Update subject
      operationId: Update-subject
      parameters:
      - description: update subject
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SubjectInput'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Update subject
      tags:
      - Субъект
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      summary: SignIn
      tags:
      - Авторизация
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.Error'
      summary: SignUp
      tags:
      - Авторизация
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
